In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(
    "../data/raw/Student_performance_data _ (1).csv"
)

In [3]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df = df.drop_duplicates()

In [6]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [7]:
X = df.drop("GPA", axis=1)

y = df["GPA"]

In [8]:
X.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,4.0

In [9]:
y.head()

0    2.929196
1    3.042915
2    0.112602
3    2.054218
4    1.288061
Name: GPA, dtype: float64

In [10]:
print("X Shape:", X.shape)

print("y Shape:", y.shape)

X Shape: (2392, 14)
y Shape: (2392,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
print("X_train:", X_train.shape)

print("X_test:", X_test.shape)

print("y_train:", y_train.shape)

print("y_test:", y_test.shape)

X_train: (1913, 14)
X_test: (479, 14)
y_train: (1913,)
y_test: (479,)

In [13]:
print(X_train.isnull().sum().sum())

print(X_test.isnull().sum().sum())

print(y_train.isnull().sum())

print(y_test.isnull().sum())

0
0
0
0

In [14]:
categorical_cols = X.select_dtypes(
    include=['object']
).columns

In [15]:
numerical_cols = X.select_dtypes(
    exclude=['object']
).columns

In [16]:
print("Categorical Columns:")

print(categorical_cols)

Categorical Columns:
Index([], dtype='str')

In [17]:
print("Numerical Columns:")

print(numerical_cols)

Numerical Columns:
Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GradeClass'],
      dtype='str')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB